### ISSUE TITLE
2023年 最新整理暑假实习

### ISSUE THREAD

**Issue by SMILY9527** [microsoft/JARVIS#102]
2023年 最新整理暑假实习（含Java，前端，测试，c++，嵌入式，算法岗），base（北京，上海，广州，深圳，杭州，西安，成都，南京）
https://github.com/0voice/enterprise_job_recommend

**Comment by hhy5562877** [comment]
这都能遇到广子



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月8日(周六) 晚上9:39
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [microsoft/JARVIS] 2023年 最新整理暑假实习 (Issue #102)




 
2023年 最新整理暑假实习（含Java，前端，测试，c++，嵌入式，算法岗），base（北京，上海，广州，深圳，杭州，西安，成都，南京）
 https://github.com/0voice/enterprise_job_recommend

**Comment by sirlaurie** [comment]
已举报

reported
