### ISSUE TITLE
is NVIDIA needed for inference_mode: local

### ISSUE THREAD

**Issue by lae5061** [microsoft/JARVIS#107]
For `inference_mode: local` do i need to have an NVIDIA GPU, or is there a settings that i can change to run this on CPU?

```

RuntimeError: Found no NVIDIA driver on your system. 
Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

```

**Comment by tricktreat** [comment]
In the latest commit, you can set the device in your config.yaml
