### ISSUE TITLE
What's wrong

### ISSUE THREAD

**Issue by youngerstyle** [microsoft/JARVIS#110]
![image](https://user-images.githubusercontent.com/7426274/230780791-db0b3fa1-e5ae-44a8-a550-c250cf7f0e6a.png)

**Comment by tricktreat** [comment]
Check web/src/api/hugginggpt.ts@Line=9

**Comment by avatarneil** [comment]
In addition to the suggestion above, looking at the server debug logs could be helpful.

If you're trying to run the standard web client, make sure you're running `models_server.py` and `awesome_chat.py` as well (make sure the chat script is is running in server mode with --mode server); examples are in the [README](https://github.com/microsoft/JARVIS#for-server).

**Comment by tricktreat** [comment]
Fixed the issue in #116, where hard-coded BASE_URL caused web pages to be unavailable in cross-host situations.
