### ISSUE TITLE
Installation failed after Jarvis consumed my /dev/sdb

### ISSUE THREAD

**Issue by panchromatic242** [microsoft/JARVIS#111]
The system requirements say only `Disk > 78G (with 42G for damo-vilab/text-to-video-ms-1.7b)`.  
When I got started I had used 29GB of my 251GB `sdb` drive. Now Jarvis is using 222GB, has taken up all the remaining space on the drive, and still has a lot more to install, partial examples below.

Did I install with the wrong flags or something?  What's the recommended fix?

I did try googling this first, but somehow the Internet seems to know almost nothing about this project. :)

```
----- Downloading from https://huggingface.co/facebook/detr-resnet-101 -----
fatal: could not create leading directories of 'facebook/detr-resnet-101': No space left on device
----- Downloading from https://huggingface.co/microsoft/speecht5_hifigan -----
fatal: could not create leading directories of 'microsoft/speecht5_hifigan': No space left on device
----- Downloading from https://huggingface.co/microsoft/speecht5_vc -----
fatal: could not create leading directories of 'microsoft/speecht5_vc': No space left on device
----- Downloading from https://huggingface.co/openai/whisper-base -----
fatal: could not create leading directories of 'openai/whisper-base': No space left on device
----- Downloading from https://huggingface.co/Intel/dpt-large -----
fatal: could not create leading directories of 'Intel/dpt-large': No space left on device
----- Downloading from https://huggingface.co/facebook/detr-resnet-50-panoptic -----
fatal: could not create leading directories of 'facebook/detr-resnet-50-panoptic': No space left on device
----- Downloading from https://huggingface.co/facebook/detr-resnet-50 -----
fatal: could not create leading directories of 'facebook/detr-resnet-50': No space left on device
----- Downloading from https://huggingface.co/google/owlvit-base-patch32 -----
fatal: could not create leading directories of 'google/owlvit-base-patch32': No space left on device
----- Downloading from https://huggingface.co/impira/layoutlm-document-qa -----
fatal: could not create leading directories of 'impira/layoutlm-document-qa': No space left on device
----- Downloading from https://huggingface.co/ydshieh/vit-gpt2-coco-en -----
fatal: could not create leading directories of 'ydshieh/vit-gpt2-coco-en': No space left on device
----- Downloading from https://huggingface.co/dandelin/vilt-b32-finetuned-vqa -----
fatal: could not create leading directories of 'dandelin/vilt-b32-finetuned-vqa': No space left on device
----- Downloading from https://huggingface.co/lambdalabs/sd-image-variations-diffusers -----
fatal: could not create leading directories of 'lambdalabs/sd-image-variations-diffusers': No space left on device
----- Downloading from https://huggingface.co/facebook/maskformer-swin-base-coco -----
fatal: could not create leading directories of 'facebook/maskformer-swin-base-coco': No space left on device
----- Downloading from https://huggingface.co/Intel/dpt-hybrid-midas -----
fatal: could not create leading directories of 'Intel/dpt-hybrid-midas': No space left on device
----- Downloading from https://huggingface.co/datasets/Matthijs/cmu-arctic-xvectors -----
fatal: could not create leading directories of 'Matthijs/cmu-arctic-xvectors': No space left on device
```

**Comment by panchromatic242** [comment]
To clarify, I know I could use the `lite` version of the install to save disk space.  Just don't know how to tell if I have enough disk to run the `standard` or `full` installs.  Thanks!

**Comment by tricktreat** [comment]
@panchromatic242 Sorry, we will correct the system requirements in the readme. In fact, we missed the disk usage of ControlNet. It took up about 126G.

**Comment by panchromatic242** [comment]
@tricktreat Hey, no worries! Thanks for hitting me back.  What total disk space should I allocate.  It's using 222GB at the moment. How much will it need?

**Comment by tricktreat** [comment]
If it is full mode, the disk usage of all required models is 78G+126G+66G=270GB . If you don't have enough disk, you can modify the code of download and models_server.py to comment out the large models to reduce the disk usage.

**Comment by panchromatic242** [comment]
OK cool. I can allocate another 100GB to that drive I think.  Just wanted to sanity check that it wasn't going to be like multiple TB of data. Thanks!

**Comment by tricktreat** [comment]
Hahahaha that won't.

**Comment by roulendz** [comment]
Install all models it took me 284GB
![image](https://user-images.githubusercontent.com/8720442/230802612-1b5e1785-921e-420f-b829-ab03ef66aa31.png)

And I used this PS script to move WSL installation to diffrent drive: https://github.com/pxlrbt/move-wsl

**Comment by panchromatic242** [comment]
@roulendz I'll have to study that a bit more, thank you.  I'm not familiar with Docker, so don't want to screw anything up. 

@tricktreat all these disk usage issues come up when downloading the models, well before the server is configured.  Would it be more efficient to have the args for the model download predicated on the user choice during server configuration?  The current process is `download all the models` then `tell the server which models to use` but it seems like `tell the server which models to use (by choosing your deployment type) and let that determine which ones to download` might be more intuitive.

**Comment by tricktreat** [comment]
Yes, thank you for the suggestion. The model loading part we will continue to improve, supporting features such as dynamically loading models as well as supporting custom models.
