### ISSUE TITLE
How many G models are downloaded by executing the command bash download.sh? How long does it take?

### ISSUE THREAD

**Issue by liujie316316** [microsoft/JARVIS#112]

**Comment by tricktreat** [comment]
At least 284GB. We now have [HF Space](https://huggingface.co/spaces/microsoft/HuggingGPT) available and you can experience our demo without deployment, with `inference_mode=hibrid` and `local_deployment=standard` settings.

**Comment by liujie316316** [comment]
> At least 284GB. We now have [HF Space](https://huggingface.co/spaces/microsoft/HuggingGPT) available and you can experience our demo without deployment, with `inference_mode=hibrid` and `local_deployment=standard` settings.

![image](https://user-images.githubusercontent.com/44899079/230834479-395b1f15-577d-48f0-8caa-5b1147f6359e.png)
When I execute this statement--python awesome_chat.py --config lite.yaml, I report the error above。

**Comment by liujie316316** [comment]
![image](https://user-images.githubusercontent.com/44899079/230834729-b142ff87-6c1c-405a-8a2e-c529c929455f.png)
lite.yaml

**Comment by liujie316316** [comment]
![image](https://user-images.githubusercontent.com/44899079/230836226-55fd24da-9962-4b8a-89d9-7ec2d55d80cb.png)

**Comment by tricktreat** [comment]
You may need to set up a proxy, in the `proxy` entry of the configuration file.

**Comment by liujie316316** [comment]
> You may need to set up a proxy, in the `proxy` entry of the configuration file.

OK,thank you.
