### ISSUE TITLE
Want to contribute to microsoft/JARVIS? If you have a bug or an idea, read the contributing guidelines before opening an issue

### ISSUE THREAD

**Issue by lumosxin** [microsoft/JARVIS#113]
#71

**Comment by lumosxin** [comment]
Have [my commit](https://github.com/microsoft/JARVIS/pull/71/files) any error, this pull requests have closed and go and modify the same thing in [your commit](https://github.com/microsoft/JARVIS/commit/0551cc185a01e9821e810b184599579f1b251835#diff-36fc287db2658d58a7b32df978e4503ffac9aa72332916823fdf8abba07697a3) and
[your commit](https://github.com/microsoft/JARVIS/commit/0551cc185a01e9821e810b184599579f1b251835#diff-affec23b9cda8e238570dd4de9b7edd5f96158215f2c000e9933169ed92b349c), Has anything difference

**Comment by tricktreat** [comment]
Sorry for the trouble. The ChatGPT included in the web is not a point of this project. We are also considering removing it to avoid annoying users #114. For less important code improvements, we will gather them into a single commit. If you want to be a contributor, please fix the bugs related to Jarvis or contribute new features, you are more than welcome to do so.

**Comment by lumosxin** [comment]
I think this problem is that the page is not optimized and prompted, so that the user does not understand what the error has occurred. This needs to be optimized, rather than removing it directly. The `data` is not defined, resulting in an error in the console, and there is no response in the page waiting. I think this should be regarded as a bug. This is a need to optimize. thanks

**Comment by tricktreat** [comment]
Hi. What I mean is that we have two pages on the front end, ChatGPT and HuggingGPT. ChatGPT is not a feature we care about and we are considering deleting it in the future.

**Comment by lumosxin** [comment]
Yes. removed it in the future, but before that there has some commits is normally, rather than `Already fixed thanks` and code same codes in your commit
