### ISSUE TITLE
Replace hard-coded 'localhost' instances with dynamic resolution for cross-PC compatibility

### ISSUE THREAD

**Issue by ma2bara** [microsoft/JARVIS#116]
The code contains hard-coded instances of 'localhost' throughout, causing issues when calling from a different PC on the same LAN or over the network. We would like this to be improved.

For example, the code in `web/src/api/hugginggpt.ts@Line=9` currently reads:
var endpoint = "http://localhost:8004/hugginggpt"

By changing it to the following, it will work properly from any PC:
`var endpoint = ${window.location.protocol}//${window.location.hostname}:8004/hugginggpt;`

There are similar instances of 'localhost' throughout the code, so we would appreciate it if you could improve them to dynamically resolve the issue.

Lastly, we would like to express our gratitude for sharing such great code. Keep up the good work!

**Comment by tricktreat** [comment]
Thanks for the suggestion. We have fixed it.
