### ISSUE TITLE
You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by liujie316316** [microsoft/JARVIS#117]
![image](https://user-images.githubusercontent.com/44899079/230842196-8450c363-caff-492c-a55c-fdd6c61e170b.png)

**Comment by liujie316316** [comment]
![image](https://user-images.githubusercontent.com/44899079/230842503-3c69e0ab-4dd4-47cc-8504-7556b0210f08.png)
ChatGPT works well, with a limit of $18 still unused, but it shows You exceeded your current quota, please check your plan and billing details

**Comment by tricktreat** [comment]
```bash
curl https://api.openai.com/v1/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "text-davinci-003",
    "prompt": "Say this is a test",
    "max_tokens": 7,
    "temperature": 0
  }'
```

**Comment by liujie316316** [comment]
> 

OK,thank you!
