### ISSUE TITLE
Can't get model server to run

### ISSUE THREAD

**Issue by oyylumo** [microsoft/JARVIS#122]
I'm running Pop!_OS 22.04 LTS x86_64 on Ryzen 5 5500 & RTX 3060 LHR.
When I run `python models_server.py --config config.yaml` according to the setup tutorial, I get this output:

```
(jarvis) callen@fatpc:~/JARVIS/server$ python models_server.py --config config.yaml
Fetching 27 files: 100%|█████████████████████████████████████████████████████████████████████████████████████| 27/27 [00:00<00:00, 23776.24it/s]
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
WARNING:datasets.builder:Found cached dataset cmu-arctic-xvectors (/home/callen/.cache/huggingface/datasets/cmu-arctic-xvectors/default/0.0.1/a62fea1f9415e240301ea0042ffad2a3aadf4d1caa7f9a8d9512d631723e781f)
Killed
```

I tried running it several times, and yesterday it got as far as generating a training split, which took a very long time and eventually ended with `Killed`. Every time I run the model server, I eventually get `Killed`.

**Comment by danimalweb** [comment]
I have the same issue.

**Comment by tricktreat** [comment]
Possibly insufficient CPU memory.

**Comment by oyylumo** [comment]
> I'm using WSL on Windows 11. I monitored usage with htop and noticed memory usage was beyond capacity even with 16GB allocated. It was necessary for me to allocate 24GB of RAM using `.wslconfig` and use a 10gb swap file in order to complete initialization and get the server running
> 
> ChatGPT lead me through troubleshooting laughing

Alright, I'll get some more ram tomorrow and see how it goes. I thought 16GB would be enough 😲

**Comment by oyylumo** [comment]
> I'm using WSL on Windows 11. I monitored usage with htop and noticed memory usage was beyond capacity even with 16GB allocated. It was necessary for me to allocate 24GB of RAM using `.wslconfig` and use a 10gb swap file in order to complete initialization and get the server running
> 
> ChatGPT lead me through troubleshooting laughing

I installed 16GB more ram and set a 10GB swap file, it is still running out of memory.

**Comment by oyylumo** [comment]
Turns out the model needed 32GB ram + ~16GB swap to not crash.
