### ISSUE TITLE
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name'

### ISSUE THREAD

**Issue by liujie316316** [microsoft/JARVIS#125]
![image](https://user-images.githubusercontent.com/44899079/231037050-8a2dd428-8616-494e-8e7d-aac4bf24211a.png)

Execute command:
python models_server.py --config config.yaml

**Comment by lierik** [comment]
You need to download the models at first. Use models/download.sh to download all relative models

**Comment by liujie316316** [comment]
> You need to download the models at first. Use models/download.sh to download all relative models

ok thank you！

**Comment by KenwayCJZX** [comment]
@lierik How can i want use local model file?
