### ISSUE TITLE
OSError: libtorch_cuda.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ttyuuuuuuuuuu** [microsoft/JARVIS#141]
运行model_server.py时发生错误，是因为torch版本不对吗？
![image](https://user-images.githubusercontent.com/51437324/231681991-a05d48ee-b5f9-4eeb-8c64-ae73785be55a.png)
![image](https://user-images.githubusercontent.com/51437324/231682081-bec4446f-5be7-449e-bc80-770fe825904d.png)
![image](https://user-images.githubusercontent.com/51437324/231682172-b6dd774e-d608-43ce-b1e0-22963af51a08.png)

我的版本是：
python==3.8.16
torch==2.0.0
![image](https://user-images.githubusercontent.com/51437324/231682425-9ccd09e0-e06c-414f-86c5-4c89c6e30af4.png)

**Comment by ttyuuuuuuuuuu** [comment]
![image](https://user-images.githubusercontent.com/51437324/231683961-6f225a8a-718e-44b6-875f-386c8f4a0cb7.png)
是不是因为这个？

**Comment by StillKeepTry** [comment]
Yes. It seems that your Nvidia driver has not been installed correctly.
