### ISSUE TITLE
Web server fails to start: The symbol "video_urls" was declared a constant here:      script

### ISSUE THREAD

**Issue by newDevPL** [microsoft/JARVIS#144]
I am getting below errors when trying to start the web server. The only thing that comes to my mind is that JARVIS repo is on a separate NVME partition but it is mounted in my home directory

`(jarvis) tomasz@JARVISGPT:~/repos/JARVIS/web$ sudo npm run dev

> vue3-ts-vite-router-tailwindcss@0.0.0 dev
> vite

  VITE v3.2.5  ready in 128 ms

  ➜  Local:   http://localhost:9999/
  ➜  Network: http://192.168.0.132:9999/
✘ [ERROR] Cannot assign to "image_urls" because it is a constant

    script:/home/tomasz/repos/JARVIS/web/src/views/home.vue?id=0:175:4:
      175 │     image_urls = [...new Set(image_urls)]
          ╵     ~~~~~~~~~~

  The symbol "image_urls" was declared a constant here:

    script:/home/tomasz/repos/JARVIS/web/src/views/home.vue?id=0:91:10:
      91 │     const image_urls = content.match(/(http(s?):|\/)([/|.|\S||\w|:|-])*?\.(?:jpg|jpeg|tiff|gif|png)/g)
         ╵           ~~~~~~~~~~

✘ [ERROR] Cannot assign to "audio_urls" because it is a constant

    script:/home/tomasz/repos/JARVIS/web/src/views/home.vue?id=0:177:4:
      177 │     audio_urls = [...new Set(audio_urls)]
          ╵     ~~~~~~~~~~

  The symbol "audio_urls" was declared a constant here:

    script:/home/tomasz/repos/JARVIS/web/src/views/home.vue?id=0:118:10:
      118 │     const audio_urls = content.match(/(http(s?):|\/)([/|.|\w|\S|:|-])*?\.(?:flac|wav)/g)
          ╵           ~~~~~~~~~~

✘ [ERROR] Cannot assign to "video_urls" because it is a constant

    script:/home/tomasz/repos/JARVIS/web/src/views/home.vue?id=0:179:4:
      179 │     video_urls = [...new Set(video_urls)]
          ╵     ~~~~~~~~~~

  The symbol "video_urls" was declared a constant here:

    script:/home/tomasz/repos/JARVIS/web/src/views/home.vue?id=0:144:10:
      144 │     const video_urls = content.match(/(http(s?):|\/)([/|.|\w|\s|:|-])*?\.(?:mp4)/g)
          ╵           ~~~~~~~~~~

Build failed with 3 errors:
script:/home/tomasz/repos/JARVIS/web/src/views/home.vue?id=0:175:4: ERROR: Cannot assign to "image_urls" because it is a constant
script:/home/tomasz/repos/JARVIS/web/src/views/home.vue?id=0:177:4: ERROR: Cannot assign to "audio_urls" because it is a constant
script:/home/tomasz/repos/JARVIS/web/src/views/home.vue?id=0:179:4: ERROR: Cannot assign to "video_urls" because it is a constant`

**Comment by tricktreat** [comment]
Already fixed, by reverting #124.
