### ISSUE TITLE
Is WSL supported?

### ISSUE THREAD

**Issue by HaroldMitts** [microsoft/JARVIS#146]
Is it possible to run in WSL?

I have gone through all of the setup, downloaded the models, etc. I have setup on a virtual machine because I am running Windows. I have an NVidia RTX 4090 on my pc, but the virtual machine running Ubuntu doesn't recognize that I have an NVidia GPU.

When I run the `python models_server.py --config config.yaml` command, I get the error:

`RunTimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx`

Bing tells me some unsupported method to get my vm to recognize the video card, but that is not appealing, since you need to first disable the GPU device on the host.

**Comment by StillKeepTry** [comment]
Based on the error descriptions, you may need to install nvidia driver. Can you detect GPU card by running `nvidia-smi`?

**Comment by HaroldMitts** [comment]
I was able to install the NVidia driver, but now I get the error that no CUDA GPUs are available when I run `python models_server.py --config config.yaml`

`RuntimeError: No CUDA GPUs are available`

**Comment by HaroldMitts** [comment]
I tried several way to get my VM to recognize the hosts GPU (an RTX 4090), but was unsuccessful. 

sudo lshw -C display, returns the following:

```
*-graphics
product: hyperv_drmdrmfb
physical ld: 1
logical name: /dev/fb0
capabilities: fb
configuration: depth=32 resolution=1024, 768
```

ChatGPT told me the following (which is less than optimistic outlook)

```
Based on the output of the sudo lshw -C display command, it looks like your system is running in a virtualized environment (Hyper-V). The "hyperv_drmdrmfb" listed under the "product" field is a virtual display driver used in Hyper-V.

Since you're running Ubuntu as a virtual machine, it's likely that you don't have a physical NVIDIA GPU installed in your system. Instead, you're using a virtualized display driver provided by the hypervisor.

As a result, you may not be able to use the NVIDIA graphics driver in your virtual machine. In this case, the virtualized graphics driver provided by the hypervisor may be the best option for displaying graphics in your virtual machine.
```

Me: `yes, I am running ubuntu in a vm in hyper v. I have an nvidia rtx 4090 on the host system. Is it possible to use this gpu in the vm?`

ChatGPT:

```
it is possible to use the NVIDIA GPU on the host system in a virtual machine running in Hyper-V. This can be done using a technology called Discrete Device Assignment (DDA), which allows you to assign a physical GPU to a virtual machine.

However, there are a few requirements that must be met in order to use DDA with an NVIDIA GPU:

Your host system must have Windows Server 2016 or later installed, and it must have the Hyper-V role enabled.

Your host system must have an NVIDIA GPU that supports Virtualization-based Security (VBS) and Input-Output Memory Management Unit (IOMMU) technologies. Most modern NVIDIA GPUs support these technologies, but you should check the specifications of your GPU to confirm.

You must have the correct drivers and firmware installed on both the host system and the virtual machine.

You must enable the GPU for DDA in the Hyper-V settings.

You must configure the virtual machine to use the assigned GPU.

Note that DDA can be a complex process, and it may require some technical expertise to set up correctly. If you're not comfortable with this process, it may be best to seek assistance from a qualified technician who can help you set up DDA correctly.
```

So, it looks like this _might_ be an option, but a complicated one with no real guarantees. 

Any suggestions or advice? How about the original WSL compatibility question? Is this supported in WSL? If so, I could just run it there, but given the complexity, I want to check here first and I could not find an answer to that anywhere online.

**Comment by HaroldMitts** [comment]
its _kinf of_ working in WSL. I need to troubleshoot a bit... but its looking promising

![image](https://user-images.githubusercontent.com/13913671/232179774-3b12a141-01d6-4272-9abf-df583cef9732.png)

I can only seem to get responses using the translate choice from the dropdown.

**Comment by HaroldMitts** [comment]
It looks like I forgot to update the WSL version... haha. anyways, I'll try that over the weekend and see if I can make some progress.

**Comment by HaroldMitts** [comment]
It turns out it is somewhat compatible. I tried a couple of times, but each time some of the models fail to load into Windows. Overall, some of the features work, when the model loaded correctly. When it didn't load correctly, the chat just says it can't do it.

I'll close this issue for now, since the original question seems to be satisfied, somewhat. 

You can see my outcome here, if interested. 
https://github.com/HaroldMitts/pub/
