### ISSUE TITLE
HuggingGPT not responding.

### ISSUE THREAD

**Issue by oyylumo** [microsoft/JARVIS#149]
I ran the tutorial commands to get the model running, I had to increase my swap file to 20GB in addition to having 32GB ram to stop models_server from running out of memory. Running `python models_server.py --config config.yaml` gives:
![image](https://user-images.githubusercontent.com/32341120/232153896-f9953f53-8036-4449-aa05-b0c556dfaab7.png)

Then running `python awesome_chat.py --config config.yaml --mode server` doesn't output anything, it just idles.

`npm run dev` gets the frontend to work, I can visit the page and send a message, but the "buffering" animation just plays on loop forever. ChatGPT works and will respond, but it doesn't interact with any of the HF models (it complained when I asked it to generate an image).

How fix?

**Comment by martin823823** [comment]
so , How fix?
