### ISSUE TITLE
cannot import name 'export_to_video' from 'diffusers.utils' 

### ISSUE THREAD

**Issue by LuoBoBo00** [microsoft/JARVIS#16]
Iraceback (most recent call last):
  File "models_server.py", line 10, in <module>
    from diffusers.utils import export_to_video
ImportError: cannot import name 'export_to_video' from 'diffusers.utils' 

I cannot download the diffusres of command verison,and i cannot find the verision on github

**Comment by tricktreat** [comment]
Hi,
`export_to_video` is a function included in the latest dev version of diffusers. We recommend installing diffusers from source. Please try `pip install git+https://github.com/huggingface/diffusers.git@8c530f#egg=diffusers` which we provide in `requirements.txt`.
