### ISSUE TITLE
JsonError : Invalide \escape fix

### ISSUE THREAD

**Issue by Rbrq03** [microsoft/JARVIS#163]
Hey guys, if you have this problem. It maybe because chatgpt generate an invalid char '\'. one simple way to solve is change code in line 218, awesome_chat.py to:
`
return text.replace('\\', '')
`
@tricktreat may you check my method and fix this bug

**Comment by tricktreat** [comment]
Thanks. I have a hard time reproducing this question. Can you provide the full illegal JSON string?
