### ISSUE TITLE
so bigger bug

### ISSUE THREAD

**Issue by g-wellsa** [microsoft/JARVIS#164]
what happed ！
Traceback (most recent call last):
  File "run_gradio_demo.py", line 4, in <module>
    from diffusers.utils import load_image
ImportError: cannot import name 'load_image' from 'diffusers.utils' (unknown location)

i find diffusers‘s source ,cannot found load_image function,so！！！

**Comment by tricktreat** [comment]
https://github.com/huggingface/diffusers/blob/3b641eabe9876e7c48977b35331fda54ce972b4a/src/diffusers/utils/testing_utils.py#L253

**Comment by g-wellsa** [comment]
i see ，thks
