### ISSUE TITLE
Can't understand the meaning of 'first'

### ISSUE THREAD

**Issue by princepride** [microsoft/JARVIS#166]
I am trying to understand the entire code but I am not familiar with Vue and some details, can anyone explain the meaning of 'first' in ChatMessage {
    role: "user" | "assistant" | "system";
    type: "text" | "image" | "audio" | "video" | "code";
    first: boolean;
    content: string;
  }

**Comment by tricktreat** [comment]
Two roles:

At the view level: it flags the first message to bind the unique style. For example: https://github.com/microsoft/JARVIS/blob/e3096e5f843401f9ca81833baafbd5b4e910cf7d/web/src/views/home.vue#L339

At the message level: it flags the real message that communicates with the backend. We use it to filter out the derived multimedia messages. For example: https://github.com/microsoft/JARVIS/blob/e3096e5f843401f9ca81833baafbd5b4e910cf7d/web/src/views/home.vue#L48

**Comment by princepride** [comment]
Thank you so much, but I have another question, Why do you need to determine the style of the message? As far as I understand, messageList is used to store all chat records, and then messageListMM is used to store the processed chat record content through regular expressions, and classify them. Therefore, the style of all messages should be text type.
```
    if (message.type != "text") {
      messageListMM.push(message)
      continue
    }
```

**Comment by tricktreat** [comment]
The messageList stores the original message, while messageListMM extracts the multimedia message from it for a more visual display.

**Comment by princepride** [comment]
Thank you for answering my question.
