### ISSUE TITLE
Error reporting in lightweight mode

### ISSUE THREAD

**Issue by jiaenqiu** [microsoft/JARVIS#175]
<img width="993" alt="image" src="https://user-images.githubusercontent.com/26378685/233249088-0f334c80-9f69-4027-9d29-e7e09ba23bc3.png">

**Comment by kittiphngsyssiri556-droid** [comment]
kittiphngsyssiri556-droid:main

**Comment by kittiphngsyssiri556-droid** [comment]
_eufhf_
