### ISSUE TITLE
Colab deployment insuffient hardware space

### ISSUE THREAD

**Issue by timleavev** [microsoft/JARVIS#18]
Hi there,
Love this idea and would love to try and contribute if possible.
Now I'm deploying it on Colab but failed a few times with the error "not enough hardware space".
I'm seeing there're close to 200G space but still running out of space in the end which is not consistant with the description of 80G required for full local model.

Please let me know if you have any questions.
Thanks,

**Comment by tricktreat** [comment]
@timleavev Hi, we have just submitted a version of Jarvis for a lightweight experience (no download or local deployment of expert models required). Run `python awesome_chat.py` directly to experience it.

**Comment by whatactuallyis** [comment]
did you have anything related to the below error @timleavev in colab?

```
ConnectionError: HTTPConnectionPool(host='localhost', port=8005): Max retries 
exceeded with url: /running (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x7fa137e2f940>: Failed to establish a new connection: [Errno 111] Connection 
refused'))
```

additionally, where can I access hugging face cookies?

**Comment by timleavev** [comment]
> did you have anything related to the below error @timleavev in colab?
> 
> ```
> ConnectionError: HTTPConnectionPool(host='localhost', port=8005): Max retries 
> exceeded with url: /running (Caused by 
> NewConnectionError('<urllib3.connection.HTTPConnection object at 
> 0x7fa137e2f940>: Failed to establish a new connection: [Errno 111] Connection 
> refused'))
> ```
> 
> additionally, where can I access hugging face cookies?

Hi @whatactuallyis Yes, I saw something similar but will circle back after I tried light experience version.
Hugging face cookies is something you can find on HuggingFace.co after registeration, you will find it in your personal profile.

**Comment by XAAIGTnG** [comment]
> did you have anything related to the below error @timleavev in colab?
> 
> ```
> ConnectionError: HTTPConnectionPool(host='localhost', port=8005): Max retries 
> exceeded with url: /running (Caused by 
> NewConnectionError('<urllib3.connection.HTTPConnection object at 
> 0x7fa137e2f940>: Failed to establish a new connection: [Errno 111] Connection 
> refused'))
> ```
> 
> additionally, where can I access hugging face cookies?

same question

**Comment by whatactuallyis** [comment]
> you will find it in your personal profile

Thanks for your quick response @timleavev. I only see access tokens and ssh keys. do they mean one of these by the cookie?

> but will circle back after I tried light experience version

would you let us know if you could find anything? thanks in advance.

**Comment by timleavev** [comment]
> > you will find it in your personal profile
> 
> Thanks for your quick response @timleavev. I only see access tokens and ssh keys. do they mean one of these by the cookie?
> 
> > but will circle back after I tried light experience version
> 
> would you let us know if you could find anything? thanks in advance.

Actually it's the token. But I still stuck on the connection refused issue in light experience. Let's wait for a solution and see if it works in the end.

**Comment by timleavev** [comment]
I'm sure that the light experience version has solved the issue on title.
But we are all facing an issue with connection refused as above.
Maybe we need your help to solve by generating a web link on Gradio?  ;)
@tricktreat  Thanks again for this amazing idea and implementation!

**Comment by tricktreat** [comment]
@timleavev If you didn't deploy local models with inference mode as `local` or `hybrid`, it will report a network error at startup. Two solutions: one is to use `huggingface` inference mode, and the other is to start a local inference endpoint. 

We are working on the Gradio demo. It will be released in the next two days. 

Thank you for your support.

**Comment by timleavev** [comment]
@tricktreat Thanks for your answer! I think the Gradio demo is going to be really exciting and look forward to it.

Another thing maybe need your clarification what is HuggingFace cookie?
I thought it was the token but running the light experience verison, I got an error saying:
Traceback (most recent call last):
  File "/content/JARVIS/server/awesome_chat.py", line 130, in <module>
    if config["huggingface"]["cookie"]:
TypeError: string indices must be integers

**Comment by tricktreat** [comment]
Because huggingface.co allows users limited use of Inference Endpoints without cookies, we recommend providing huggingface cookies to Jarvis. It is not a huggingface token and can be obtained as follows:

![image](https://user-images.githubusercontent.com/25740077/229746060-7be5d443-2abe-4de5-8172-2bbb9f3d3e5c.png)

**Comment by whatactuallyis** [comment]
thank you for your response @tricktreat. I got it working but once I write something in the [User] section. I get `KeyError: 'choices'`. what might I be doing wrong?

**Comment by tricktreat** [comment]
@timleavev Something went wrong with the request to the LLM, please check your OpenAI Key.
