### ISSUE TITLE
importError

### ISSUE THREAD

**Issue by mijunhua** [microsoft/JARVIS#183]
python models_server.py --config configs/config.default.yaml

Traceback (most recent call last):
  File "/home/ml/docker/projects/JARVIS/server/models_server.py", line 29, in <module>
    from controlnet_aux import OpenposeDetector, MLSDdetector, HEDdetector, CannyDetector, MidasDetector
ImportError: cannot import name 'CannyDetector' from 'controlnet_aux' (/home/ml/miniconda3/lib/python3.10/site-packages/controlnet_aux/__init__.py)

some debug suggestions？

**Comment by whatactuallyis** [comment]
@mijunhua How was it solved?

**Comment by Value-Jack** [comment]
hi, guys, how do you sovle this promblem?
