### ISSUE TITLE
suggestion to requirement.txt install failure

### ISSUE THREAD

**Issue by samqin123** [microsoft/JARVIS#19]
pip install controlnet-aux==0.0.1 

requirement.txt 前3项如果出现安装问题，可以下载后，copy到javis环境目录
第三个，直接使用上面的pip安装。

**Comment by tricktreat** [comment]
It is recommended to install controlnet-aux from the source code, ref: https://github.com/patrickvonplaten/controlnet_aux/issues/11#issuecomment-1482229305

**Comment by siyiding1216** [comment]
got this error from espnet
gcc -pthread -B /home/ubuntu/miniconda3/envs/jarvis/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ilib/World/src -I/tmp/pip-build-env-xvfzkw5i/overlay/lib/python3.8/site-packages/numpy/core/include -I/home/ubuntu/miniconda3/envs/jarvis/include/python3.8 -c lib/World/src/cheaptrick.cpp -o build/temp.linux-x86_64-cpython-38/lib/World/src/cheaptrick.o
      /tmp/pip-build-env-xvfzkw5i/overlay/lib/python3.8/site-packages/setuptools/dist.py:788: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      error: command 'gcc' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
