### ISSUE TITLE
Are there plans to release the task planning evaluation procedure and datasets?

### ISSUE THREAD

**Issue by downeykking** [microsoft/JARVIS#218]
As title. The latest revision of the ArXiv paper suggests a task planning evaluation procedure and datasets, but I can't seem to find that dataset anywhere. Are there any plans to release this dataset in the future?

Sorry if I've missed it somewhere but thanks regardless!

The same issues are like follows:
#205 #208

**Comment by StillKeepTry** [comment]
Hi, @downeykking  Thanks for your attention. We are currently working with our labeling teams to iteratively improve the quality of this dataset and our legal team to ensure compliance of the dataset release. We will release a work about this dataset in the future. please be patient.

**Comment by downeykking** [comment]
Got it, thanks!
