### ISSUE TITLE
Can Nvidia's 40 series graphics card be used for the current project?

### ISSUE THREAD

**Issue by GothicFox** [microsoft/JARVIS#22]
Can Nvidia's 40 series graphics card be used for the current project?

as I can see that the System Requirements is as follows: 

Ubuntu 16.04 LTS
NVIDIA GeForce RTX 3090 * 1
RAM > 24GB

**Comment by singlag** [comment]
> RTX 3090

maybe 24GB vram is a must

**Comment by Explorergt92** [comment]
I've got it running with a 4070ti, it's using 35-48GB of RAM and 2.6-3.5GB VRAM

**Comment by RaSan147** [comment]
The SYSTEM REQUIREMENTS is provided

**Comment by peng12175** [comment]
yes
