### ISSUE TITLE
The model `text-davinci-003` has been deprecated

### ISSUE THREAD

**Issue by dtlzhuangz** [microsoft/JARVIS#236]
I have tried the example case following the server mode and cli mode. Both return "The model `text-davinci-003` has been deprecated"
![image](https://github.com/microsoft/JARVIS/assets/139844877/e5a174f5-1448-442a-8d7a-33d528a92a81)
![image](https://github.com/microsoft/JARVIS/assets/139844877/0a65ace3-7281-4121-ae3b-8b88aaeeb22c)
Could you help me solve the problem?

**Comment by dtlzhuangz** [comment]
modify the 'model' in config.default.yaml 'text-davinci-003'. Closed

**Comment by dtlzhuangz** [comment]
Modify the 'model' in config.default.yaml into gpt3 or gpt4 and 'use_completion' into false will fix it

**Comment by rekcodman** [comment]
I wrote this guide if you need further guidance : https://rekcodman.gitbook.io/972
