### ISSUE TITLE
"Encountered 8 files may not copied correctly on windows"

### ISSUE THREAD

**Issue by meeeo** [microsoft/JARVIS#27]
![Screenshot_20230405-050328292_1](https://user-images.githubusercontent.com/5188710/229922751-2dd35e99-31ce-4048-a530-51d4b0f13cc4.jpg)

Have this when downloading models.
And I think models disk usage should also be listed on system requirements.

**Comment by tricktreat** [comment]
@meeeo  Thanks for your suggestion. You have downloaded successfully. We will also reduce the number of models that need to be deployed locally in these days to make the disk and memory usage smaller.
