### ISSUE TITLE
ModuleNotFoundError: No module named 'diffusers'

### ISSUE THREAD

**Issue by 1nnovat1on** [microsoft/JARVIS#30]
On windows 11
16 GB RAM
12th Gen Intel(R) Core(TM) i7-12700F
NVIDIA GeForce RTx3070

Command: python awesome_chat.py --config config.yaml --mode cli

Error:
 File ".\JARVIS\server\awesome_chat.py", line 17, in <module>
    from diffusers.utils import load_image
ModuleNotFoundError: No module named 'diffusers'

**Comment by Explorergt92** [comment]
That should've installed with 'pip install -r requirements.txt' ... but you can try running 'pip install diffusers'
