### ISSUE TITLE
Error:OSError: You seem to have cloned a repository without having git-lfs installed.

### ISSUE THREAD

**Issue by tangyipeng100** [microsoft/JARVIS#37]
Encounter an error:
```bash
Error:OSError: You seem to have cloned a repository without having git-lfs installed. Please install git-lfs and run `git lfs install` followed by `git lfs pull` in the folder you cloned.
```
How to solve this problem when running
```bash
python models_server.py --config config.yaml
```

**Comment by ErikDombi** [comment]
`git-lfs` needs to be installed when downloading the models. The quickest way to fix this would be to install git-lfs first, then run `git lfs install`, then re-run the download script.

**Comment by samqin123** [comment]
use this "brew install git-lfs" if you have install homebrew. or you can download and install here https://git-lfs.com/

**Comment by ErikDombi** [comment]
I think you're better off just using `apt-get install git-lfs` if you're on Ubuntu as the requirements say

**Comment by aisensiy** [comment]
Install `git-lfs` and then rerun the command `bash download.sh` in `server/models` directory can be helpful.

**Comment by PhoebeChen123** [comment]
I have installed git-lfs, but there is still this error. Why?
