### ISSUE TITLE
Whisper-base model cannot be loaded

### ISSUE THREAD

**Issue by vladcorbu** [microsoft/JARVIS#40]
Hi guys, when I'm running python models_server.py --config config.yaml I get this error:

raise ValueError(f"Could not load model {model} with any of the following classes: {class_tuple}.")
ValueError: Could not load model models/openai/whisper-base with any of the following classes: (<class 'transformers.models.auto.modeling_auto.AutoModelForCTC'>, <class 'transformers.models.auto.modeling_auto.AutoModelForSpeechSeq2Seq'>, <class 'transformers.models.whisper.modeling_whisper.WhisperForConditionalGeneration'>).

**Comment by suamai** [comment]
I am having the same error, why was this closed?

**Comment by estoldy** [comment]
Same here, @vladcorbu did you manage to get it fixed?

**Comment by longgui0318** [comment]
@suamai @e-oldman  Need to complete tool installation

```
apt-get install git-lfs
```
