### ISSUE TITLE
Would it support Azure OpenAI?

### ISSUE THREAD

**Issue by Ko-Ko-Kirk** [microsoft/JARVIS#45]
Hi, I only saw OpenAI API key in config.yml. Does it support Azure OpenAI? Or is there any plans to support Azure OpenAI?

**Comment by StillKeepTry** [comment]
We will support Azure OpenAI in a few days. Please be patient.

**Comment by tosaddler** [comment]
> We will support Azure OpenAI in a few days. Please be patient.

I'm sorry, are you asking us to be patient when the future is literally staring us right in the face? Nuh uh, I don't think so. You have JARVIS, make him update the code and work faster! Just teasing, thank you to everyone working on this project...
