### ISSUE TITLE
Is nvidia 4070ti enough to run this model?

### ISSUE THREAD

**Issue by hsju2021** [microsoft/JARVIS#46]
I don't quite understand the requirement being rtx 3090.
Is it the vram that matters?

**Comment by tricktreat** [comment]
Check the list of local models https://github.com/microsoft/JARVIS/blob/1b7351687309943ea550568e66d483e6cdf1c56b/server/models/download.sh. If it can fit the largest model, then that's basically fine. Sometimes several models run in parallel, and you may get OOM errors.

**Comment by hsju2021** [comment]
> I've got it running on a 4070ti and it hasn't used over 4GB VRAM in my testing, but it is using 35-48GB of my 64GB of system memory using the hybrid full configuration so I am assuming it's pulling the larger models from Huggingface when it needs them.
> 

Thanks for your reply. Can you also tell me how much storage space is needed to download the models?

**Comment by Ryan2009** [comment]
> 

Can 4070ti run Jarvis? Do you suggest  I  buy a new 4070ti  to run JARVIS ? The 4080 and 4090 is so expensive

**Comment by BoruchYonasan** [comment]
I have 32GB RAM and 16GB VRAM, if 4GB VRAM is the max @Explorergt92 is seeing and instead much more RAM is being utilized, is it possible for my system to run Jarvis?
