### ISSUE TITLE
Error loading model whisper-base

### ISSUE THREAD

**Issue by suamai** [microsoft/JARVIS#51]
While trying to run the models server I run into the following error:

```
raise ValueError(f"Could not load model {model} with any of the following classes: {class_tuple}.")
ValueError: Could not load model models/openai/whisper-base with any of the following classes: (<class 'transformers.models.auto.modeling_auto.AutoModelForCTC'>, <class 'transformers.models.auto.modeling_auto.AutoModelForSpeechSeq2Seq'>, <class 'transformers.models.whisper.modeling_whisper.WhisperForConditionalGeneration'>).
```

I tried redoing all the installation steps, removing and recreating the conda env, and making sure all python dependencies are installed and both api tokens configured. What could be going wrong?

**Comment by ErikDombi** [comment]
Did you have `git lfs` installed prior to downloading the models?
