### ISSUE TITLE
Getting no response when using lite.yaml as config for server mode

### ISSUE THREAD

**Issue by harry1931** [microsoft/JARVIS#56]
I'm not getting any responses when using lite yaml  "python awesome_chat.py --config lite.yaml --mode server" , CLI mode works fine tho, wondering if anyone encontered the same issue?

![Screenshot 2023-04-06 074715](https://user-images.githubusercontent.com/38419516/230237999-b56aac0b-89a6-4766-9fa6-352252773003.png)

**Comment by tricktreat** [comment]
@harry1931 Hi. The server starts without a user-friendly message. In your case, the server might have already started. Please try:

```bash
curl --location 'http://localhost:8004/tasks' \
--header 'Content-Type: application/json' \
--data '{
    "messages": [
        {
            "role": "user",
            "content": "based on pose of /examples/d.jpg and content of /examples/e.jpg, please show me a new image"
        }
    ]
}'
```
