### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by e-oldman** [microsoft/JARVIS#58]
Clean install. The server is running.

Ubuntu 22.04
Firefox/Chrome

```
cd web/
npm run dev
```

Result of submitting any prompt:
![image](https://user-images.githubusercontent.com/13213650/230265930-8804578e-8376-4caa-805b-11825fc2f6bf.png)

With the following in the console:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8004/hugginggpt. (Reason: CORS request did not succeed). Status code: (null).
```

**Comment by tricktreat** [comment]
Hi, can you show the output from the last few server/logs/debug.logs?

**Comment by e-oldman** [comment]
`debug.log` is empty in this case. 

The request sent from the frontend cannot reach the `/hugginggpt` endpoint on the localhost. The server is up and running.

**Comment by tricktreat** [comment]
Please try the latest commit to see if it solves your issue. Note that: if you are running the web client on another machine, you need to set `http://{LAN_ip_of_the_server}:{port}/` to `web/src/api/hugginggpt.ts@Line=9`.
