### ISSUE TITLE
awesome_chat.py returns error about openai api key

### ISSUE THREAD

**Issue by HaroldMitts** [microsoft/JARVIS#63]
I have quadruple checked my openai api key is correct. I copied and pasted it to avoid typo, I even generated a new key after many attempts/fails. However, no matter what key I generate and write to config.yaml, when I run awesome_chat.py it insists that I have an incorrect openai key. 

I also tried running npm run dev and the browser opens and I see the HuggingGPT page and text box, but anytime I submit any prompt, system returns "Something seems seems wrong". Interestingly, localhost is opened to port 9999 when running npm run dev, but in config.yaml it has localhost port set to 8003. 

What is it I am doing wrong? I feel like I am so close, but so far. :)

**Comment by tricktreat** [comment]
@HaroldMitts Sorry for the trouble. Let me try to solve it for you. First let me know if your OpenAI Key starts with 'sk-'? Also what is the commit id of the JARVIS you are using.

**Comment by zzfoo** [comment]
> I have quadruple checked my openai api key is correct. I copied and pasted it to avoid typo, I even generated a new key after many attempts/fails. However, no matter what key I generate and write to config.yaml, when I run awesome_chat.py it insists that I have an incorrect openai key.
> 
> I also tried running npm run dev and the browser opens and I see the HuggingGPT page and text box, but anytime I submit any prompt, system returns "Something seems seems wrong". Interestingly, localhost is opened to port 9999 when running npm run dev, but in config.yaml it has localhost port set to 8003.
> 
> What is it I am doing wrong? I feel like I am so close, but so far. :)

maybe you need to modify lite.yaml instead. when running `python awesome_chat.py --config lite.yaml` the error message  "Incrorrect OpenAI key. Please check your config.yaml file." is misleading, since it is actually using lite.yaml.

**Comment by HaroldMitts** [comment]
> 
@tricktreat The OpenAI API key does conform with the requirements and begins with sk- also, how do I check the commit ID?

@zzfoo I did try adding both keys to the lite.yaml and it is returning the same error

In general, I should be able to modify either yaml file key values, save the file(s), then rerun the commands to use either the browser or cli without restarting anything else, right?

**Comment by tricktreat** [comment]
This error is only reported if the code is satisfied:
```python
if not config["openai"]["key"].startswith("sk-") and config["openai"]["key"]!="gradio":
    raise ValueError("Incrorrect OpenAI key. Please check your config.yaml file.")
```

**Comment by HaroldMitts** [comment]
I added the double quotes around the hard-coded OpenAI API key and also around the Huggingface token, and it seems to have gotten past this issue. 

I don't know if it is true, but if true, it seems like should be in the documentation.

**Comment by HaroldMitts** [comment]
Following this, I think I will close this ticket. I got it working. Thanks for the help.
![image](https://user-images.githubusercontent.com/13913671/230503980-b0d7d72f-8ea5-4d65-b24d-d06e3ce608a3.png)
