### ISSUE TITLE
The result looks not good to me

### ISSUE THREAD

**Issue by aisensiy** [microsoft/JARVIS#64]
![2131680772770_ pic](https://user-images.githubusercontent.com/661860/230333418-f13c8b73-948f-48fd-8100-f48f44df1ad6.jpg)

**Comment by tricktreat** [comment]
Javis relies on the predictions of the expert models to solve the user's request. If the expert models do not yield useful information, Jarvis also has a hard time making decisions.

There are a few tips to make Jarvis perform better:

- If Jarvis has problems with task planning, add or replace examples in the demonstrations we provide.
- If Jarvis selects inappropriate models, we suggest you increase the maximum model description length `max_description_length`. 
- Increase the number of candidate models `num_candidate_models`. With this setting, Jarvis can select useful models from a larger range of models.
- Select the models you think are useful for your request and deploy them locally, then provide the model description in `server/data/p0_models.jsonl`. Jarvis can dynamically accommodate expert models (tools) and dispatch tasks to the expanded expert models based on the model descriptions provided.
