### ISSUE TITLE
models_server.py  returns error

### ISSUE THREAD

**Issue by fengguangqin** [microsoft/JARVIS#70]
(jarvis) [root@myflink server]# python models_server.py --config config.yaml
Traceback (most recent call last):
  File "models_server.py", line 10, in <module>
    from diffusers.utils import export_to_video
ImportError: cannot import name 'export_to_video' from 'diffusers.utils' (/root/anaconda3/envs/jarvis/lib/python3.8/site-packages/diffusers/utils/__init__.py)

**Comment by StillKeepTry** [comment]
This issue https://github.com/microsoft/JARVIS/issues/16 maybe help you.
