### ISSUE TITLE
/lib/x86_64-linux-gnu/libssl.so.10: version `libssl.so.10' not found

### ISSUE THREAD

**Issue by liujie316316** [microsoft/JARVIS#82]
![image](https://user-images.githubusercontent.com/44899079/230523954-fb48f833-4059-420a-bfd4-101131396a7a.png)

**Comment by liujie316316** [comment]
![image](https://user-images.githubusercontent.com/44899079/230525198-c20b65b4-d04f-451f-b05a-fa851dd7a6f6.png)

**Comment by StillKeepTry** [comment]
Maybe you can upgrade openSSL.

**Comment by liujie316316** [comment]
> Maybe you can upgrade openSSL.

What version should OpenSSL be upgraded to?I am currently at 3.1.0

**Comment by liujie316316** [comment]
![image](https://user-images.githubusercontent.com/44899079/230541969-1df50820-3ff1-4c67-989f-9dd525b4b119.png)
Currently, this error is reported, but libssl.so.10 can be found in folder /lib/x86_64-linux-gnu

**Comment by StillKeepTry** [comment]
Maybe this [link](https://henchat.net/%E6%89%BE%E4%B8%8D%E5%88%B0libssl-so-10%E7%9A%84%E7%BB%88%E6%9E%81%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88-ubuntu-18/) is useful for you.

**Comment by liujie316316** [comment]
> Maybe this [link](https://henchat.net/%E6%89%BE%E4%B8%8D%E5%88%B0libssl-so-10%E7%9A%84%E7%BB%88%E6%9E%81%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88-ubuntu-18/) is useful for you.

I have seen this link before. After installing it, the version of OpenSSL is lower and needs to be uninstalled and reinstalled

**Comment by JiahengZeng** [comment]
hello, same problem, have you solved it?
