### ISSUE TITLE
What does 72G of disk space refer to？

### ISSUE THREAD

**Issue by CanIbeyourdog** [microsoft/JARVIS#86]
Dear jarvis team：
     I'm sure my device has more than 72G of space. But when I run download.sh, it remains me "no space left on device".  I used df -h to check my disk, and It was indeed full. Could you tell me what does 72G of disk space refer to？How much space do I need to run download.sh?

**Comment by StillKeepTry** [comment]
Actually, it requires at least 78G disk space. But you can use the Minimum setting, which uses HuggingFace Inference Endpoints.

### Default

+ Ubuntu 16.04 LTS
+ VRAM >= 12GB
+ RAM > 12GB (minimal), 16GB (standard), 42GB (full)
+ Disk > 78G (with 42G for `damo-vilab/text-to-video-ms-1.7b`)

**Comment by StillKeepTry** [comment]
We are also optimizing the usage of `damo-vilab/text-to-video-ms-1.7b` since it costs too much space.

**Comment by CanIbeyourdog** [comment]
Thanks for your reply!  
What I mean is maybe 78G is not enough for download those models. Before I run download.sh, there was 160G available in my disk. But after it downloaded 3 folders, it stopped and ran out of my storage space.
I'll try lite.yaml and use the Minimum setting to experience this cool work, thank you!
