### ISSUE TITLE
urllib3.exceptions.NewConnectionError: Failed to establish a new connection: [Errno 110] Connection timed out

### ISSUE THREAD

**Issue by liujie316316** [microsoft/JARVIS#88]
![image](https://user-images.githubusercontent.com/44899079/230589107-6cb11f7f-34b8-4723-8dc7-ec49b372fbcc.png)

**Comment by tricktreat** [comment]
Hi, please make sure your network can access the OpenAI API. If not, setting up a proxy might work.
