### ISSUE TITLE
建议发展一个替代chatgpt的选择，避免过早被拒访问而影响开源进展

### ISSUE THREAD

**Issue by rexiyz** [microsoft/JARVIS#9]
据以往经验，为chatgpt这种在国内访问已被拒的生态组件做项目，如果做得好，都会受到审查牵连，影响后面的商业化进程，不是能翻就ok的，望重视早日落地成功

**Comment by 623059008** [comment]
ChatGPT API can be replaced by Azure OpenAI API.

**Comment by ucas010** [comment]
微软不也是美国的么？而且openai还是微软投资的。。。就看微软是否重视国内市场了。

**Comment by xiangdeyizhang** [comment]
别人本来就是美国的，你爱用不用，这些技术都是美国的。

**Comment by wangyuxinwhy** [comment]
> 别人本来就是美国的，你爱用不用，这些技术都是美国的。

这建议没什么不妥，你没必要应激。项目本身的配置中就有  model 字段来配置 LLM 控制器的类型，此项目支持更多类型的控制器，有什么不好吗？这不是即符合此项目开发者的初衷，又符合各地区法律规定，又有利于开源项目的运作？

**Comment by ybsun0215** [comment]
> Azure OpenAI API.

OPENAPI 跟CHATGPT有区别吗？

**Comment by tricktreat** [comment]
@rexiyz  Thanks for the suggestion. We will expand the supported LLMs to cover open ones.
