### ISSUE TITLE
"Something Went Wrong" -- Receiving end does not exist

### ISSUE THREAD

**Issue by heathriel** [microsoft/JARVIS#93]
I see other reported issues with this, but this seems different.

Everything is running properly, and the cli is running correctly, but when I connect to the web service, I get "Something Seems Wrong". 

Console says:

Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist

<img width="329" alt="Screenshot 2023-04-07 at 2 24 57 PM" src="https://user-images.githubusercontent.com/6154689/230682108-eb8135ae-9fbc-4f90-8650-704c802ad230.png">

<img width="534" alt="Screenshot 2023-04-07 at 2 41 43 PM" src="https://user-images.githubusercontent.com/6154689/230682418-d0ce7439-694e-4789-8aad-29cf9144ce1b.png">

<img width="561" alt="Screenshot 2023-04-07 at 2 24 37 PM" src="https://user-images.githubusercontent.com/6154689/230682111-662e6047-af04-401b-85dd-fda3f7614ec1.png">

Not sure where the disconnect is or how to fix. Do I need to update the config.yaml from localhost to the server IP?

**Comment by tricktreat** [comment]
Does the HTTP request work with CURL?

```bash
curl --location 'http://localhost:8004/tasks' \
--header 'Content-Type: application/json' \
--data '{
    "messages": [
        {
            "role": "user",
            "content": "based on pose of /examples/d.jpg and content of /examples/e.jpg, please show me a new image"
        }
    ]
}'
```

**Comment by tricktreat** [comment]
Please try the latest commit to see if it solves your issue. Note that: if you are running the web client on another machine, you need set `http://{LAN_ip_of_the_server}:{port}/` to `web/src/api/hugginggpt.ts@Line=9`.
