### ISSUE TITLE
Introduction of gradio broke `web` client.

### ISSUE THREAD

**Issue by avatarneil** [microsoft/JARVIS#95]
I believe that 4caa8aafe129fa54ccfdd986056b76ead4873457 broke the legacy `web` client's handling of the openaikey.

In `server/awesome_chat.py`, it appears that the server is always attempting to pull the openaikey out from the request, rather than the config file. This is an issue with the basic web client found in the `web` folder, as it has nowhere to supply an API key.

Is there any appetite for me to create a PR to make the browser-provided token a fallback in case of a key not being in `config.yaml`, so users can still use the non-gradio client?

**Comment by tricktreat** [comment]
`HEADER` reads `OPENAI_KEY` from the config by default. At https://github.com/microsoft/JARVIS/blob/0551cc185a01e9821e810b184599579f1b251835/server/awesome_chat.py#L168-L172, only if `openaikey` exists , the Header will just use the `openaikey` from the request.

**Comment by avatarneil** [comment]
I think that this may have to do with multiprocessing spawning off a new task, where it can no longer access the same `global HEADER`; could that be the case? I'm not abundantly familiar with globally scoped variables and multiprocessing in Python; but I am quite certain that the tweak I implemented in #96 solves my problem.

At the very least, it would probably make sense to consolidate down the logic so `HEADER` is only ever set within the `REQUEST`, and there's no mutation in the global scope.

Do you see any reason to not just drop https://github.com/microsoft/JARVIS/blob/0551cc185a01e9821e810b184599579f1b251835/server/awesome_chat.py#L82-87 in conjunction with the changes in #96, so that the logic for handling the API Key is more centralized inside of the `send_request` method?

**Comment by tricktreat** [comment]
Yes, I agree with you. A unified form would also make the code logic clearer.
